[package]
name = "from_png_to_jpeg"
version = "0.1.0"
authors = ["BinaryDolphin29"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
chrono = "0.4.19"